---
Name: modelascontrollerroutes
After: '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    '': 'SilverStripe\CMS\Controllers\RootURLController'
    'RemoveOrphanedPagesTask//$Action/$ID/$OtherID': 'SilverStripe\CMS\Tasks\RemoveOrphanedPagesTask'
    'SiteTreeMaintenanceTask//$Action/$ID/$OtherID': 'SilverStripe\CMS\Tasks\SiteTreeMaintenanceTask'
    '$URLSegment//$Action/$ID/$OtherID': 'SilverStripe\CMS\Controllers\ModelAsController'
---
Name: legacycmsroutes
Before: '#modelascontrollerroutes'
---
SilverStripe\Control\Director:
  rules:
    'admin/cms': '->admin/pages'
